config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolios, except: [:show]
  get 'angular-items', to: 'portfolios#angular' 
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
  
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'


  resources :blogs do
  	member do
  		get :toggle_status
  	end
  end
  
  root to: 'pages#home'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <title><%= @page_title %></title>
  <%= csrf_meta_tags %>

  <meta name="keywords" content="<%= @seo_keywords %>" />

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
 <div class="site-wrapper">

  <div class="site-wrapper-inner">

    <div class="cover-container">

      <%= render "shared/application_nav" %>

      <%= yield %>

      <%= render "shared/application_footer" %>

      <%= source_helper %>

    </div>
  </div>
</div>


</body>
</html>

app/views/layouts/blog.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title><%= @page_title %></title>
    <%= csrf_meta_tags %>

    <meta name="keywords" content="<%= @seo_keywords %>" />

    <%= stylesheet_link_tag    'blogs', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


  <body>

  	<%= render 'shared/blog_nav' %>

    <div class="blog-header">
      <div class="container">
        <h1 class="blog-title">The Worst Blog Ever</h1>
        <p class="lead blog-description">An example blog template built with Bootstrap.</p>
        <%= link_to 'Write a New Blog', new_blog_path if logged_in?(:site_admin) %>
      </div>
    </div>


    <div class="container">

      <div class="row"> 

        <%= yield %>

        <div class="col-sm-3 offset-sm-1 blog-sidebar">
          <div class="sidebar-module sidebar-module-inset">
            <h4>About</h4>
            <p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
          </div>
          <div class="sidebar-module">
            <h4>Archives</h4>
            <ol class="list-unstyled">
              <li><a href="#">March 2014</a></li>
              <li><a href="#">February 2014</a></li>
              <li><a href="#">January 2014</a></li>
              <li><a href="#">December 2013</a></li>
              <li><a href="#">November 2013</a></li>
              <li><a href="#">October 2013</a></li>
              <li><a href="#">September 2013</a></li>
              <li><a href="#">August 2013</a></li>
              <li><a href="#">July 2013</a></li>
              <li><a href="#">June 2013</a></li>
              <li><a href="#">May 2013</a></li>
              <li><a href="#">April 2013</a></li>
            </ol>
          </div>
          <div class="sidebar-module">
            <h4>Elsewhere</h4>
            <ol class="list-unstyled">
              <li><a href="#">GitHub</a></li>
              <li><a href="#">Twitter</a></li>
              <li><a href="#">Facebook</a></li>
            </ol>
          </div>
        </div><!-- /.blog-sidebar -->

         </div>

        <footer class="blog-footer">
          <p>Blog template built for <a href="https://getbootstrap.com">Bootstrap</a> by <a href="https://twitter.com/mdo">@mdo</a>.</p>
          <p>
            <a href="#">Back to top</a>
          </p>
        </footer>



        

     
    
    </div>

    
    <% if session[:source] %>
      <p>You are a Sea lion visiting from <%= session[:source] %></p>
    <% end %>
  </body>
</html>

app/views/layouts/portfolio.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @page_title %></title>
    <%= csrf_meta_tags %>

    <meta name="keywords" content="<%= @seo_keywords %>" />

    <%= stylesheet_link_tag    'portfolios', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= render "shared/nav", location: 'top' %>

    <%= login_helper %>

    <%= yield %>

    <h3>Magin mountain</h3>
    <% if session[:source] %>
      <p>You are a Sea lion visiting from <%= session[:source] %></p>
    <% end %>
  </body>
</html>